language: python
matrix:
    include:
        - name: "Python 3.7 on Windows"
          os: Windows
          language: shell
          before_install:
            - choco install python
            - python -m pip install --upgrade pip
          env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - cd PythonPlays
  - pip install -r requirements.txt
  - cd ..
  - cd PlayRecorder
  - pip install -r requirements.txt
  - cd ..
  - cd CoreComponents
  - pip install -r requirements.txt
  - cd ..
script:
  - python -m unittest discover 
