language: python
python: "3.6"
install:
  - cd PythonPlays
  - pip install -r requirements.txt
  - cd ..
  - cd PlayRecorder
  - pip install -r requirements.txt
  - cd ..
  - cd CoreComponents
  - pip install -r requirements.txt
  - cd ..
  script:
  - python -m unittest discover 
